"""
DataFlow DAG YAML → Airflow DagBag Integration Test
====================================================
Tests that dag-factory compatible YAML files generated by DataFlow
can be successfully loaded into Airflow 3.x DagBag.

Tests:
  1. Each YAML file parses and builds DAGs via dag-factory
  2. DAG IDs follow the dataflow__ convention
  3. Tasks are created with correct operator classes
  4. Task dependencies are wired correctly
  5. Default args propagate (owner, retries, etc.)
  6. Schedule is set correctly
  7. Bulk load_yaml_dags works (simulates real Airflow dagbag scan)
  8. Bootstrap generate_dags.py loads all YAMLs
  9. Advanced features YAML with mapping_file references
  10. Realistic pipeline_tasks.py has all expected callables
  11. PySpark script stub has all expected functions
"""

import os
import sys
import traceback
import yaml
import tempfile
import shutil
import importlib.util
import json

os.environ.setdefault("AIRFLOW_HOME", tempfile.mkdtemp())
os.environ["AIRFLOW__CORE__LOAD_EXAMPLES"] = "False"
os.environ["AIRFLOW__DATABASE__SQL_ALCHEMY_CONN"] = "sqlite:////tmp/airflow_test.db"
os.environ["AIRFLOW__CORE__UNIT_TEST_MODE"] = "True"

import airflow
from airflow.models import DagBag
from dagfactory.dagfactory import _DagFactory, load_yaml_dags

TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
STUBS_DIR = os.path.join(TESTS_DIR, "stubs")
MAPPINGS_DIR = os.path.join(STUBS_DIR, "mappings")

YAML_FILES = [
    "flat_file_landing_to_raw.yaml",
    "db_extract_to_dwh.yaml",
    "flat_file_with_transform.yaml",
    "simple_no_sensor.yaml",
    "advanced_features.yaml",
]

PASS = 0
FAIL = 0
ERRORS = []

def check(label, condition, detail=""):
    global PASS, FAIL, ERRORS
    if condition:
        PASS += 1
        print(f"  PASS  {label}")
    else:
        FAIL += 1
        msg = f"  FAIL  {label}" + (f" — {detail}" if detail else "")
        print(msg)
        ERRORS.append(msg)

def test_individual_yaml_files():
    print("\n" + "=" * 60)
    print("TEST 1: Individual YAML file loading via dag-factory")
    print("=" * 60)

    for fname in YAML_FILES:
        fpath = os.path.join(TESTS_DIR, fname)
        print(f"\n--- {fname} ---")

        with open(fpath) as f:
            raw = yaml.safe_load(f)

        dag_ids = [k for k in raw.keys() if not k.startswith("default")]
        check(f"[{fname}] YAML parsed OK", len(dag_ids) > 0, f"dag_ids={dag_ids}")

        try:
            factory = _DagFactory(config_filepath=fpath)
            dags = factory.build_dags()
            check(f"[{fname}] build_dags() succeeded", True)
            check(f"[{fname}] DAG count matches", len(dags) == len(dag_ids),
                  f"expected {len(dag_ids)}, got {len(dags)}")

            for dag_id, dag in dags.items():
                check(f"[{fname}] DAG ID starts with 'dataflow__'",
                      dag_id.startswith("dataflow__"), f"got: {dag_id}")
                check(f"[{fname}] DAG has tasks",
                      len(dag.tasks) > 0, f"task count: {len(dag.tasks)}")

                task_ids = [t.task_id for t in dag.tasks]
                print(f"    Tasks: {task_ids}")

                dag_config = raw[dag_id]

                expected_schedule = dag_config.get("schedule")
                actual_schedule = dag.timetable.serialize() if hasattr(dag, 'timetable') else str(dag.schedule_interval)
                print(f"    Schedule: {expected_schedule} → {actual_schedule}")

                expected_owner = dag_config.get("default_args", {}).get("owner", "airflow")
                for t in dag.tasks:
                    check(f"[{fname}] task '{t.task_id}' owner = '{expected_owner}'",
                          t.owner == expected_owner, f"got: {t.owner}")
                    break

                for task_name, task_config in dag_config.get("tasks", {}).items():
                    deps = task_config.get("dependencies", [])
                    if deps:
                        task = dag.get_task(task_name)
                        upstream_ids = [t.task_id for t in task.upstream_list]
                        check(f"[{fname}] task '{task_name}' upstream deps",
                              set(deps) == set(upstream_ids),
                              f"expected {deps}, got {upstream_ids}")

        except Exception as e:
            check(f"[{fname}] build_dags() succeeded", False, f"Error: {e}")
            traceback.print_exc()


def test_load_yaml_dags_bulk():
    print("\n" + "=" * 60)
    print("TEST 2: Bulk load_yaml_dags (simulating Airflow dagbag scan)")
    print("=" * 60)

    g = {}
    try:
        load_yaml_dags(globals_dict=g, dags_folder=TESTS_DIR)
        dag_ids = [k for k in g.keys() if k.startswith("dataflow__")]
        check("load_yaml_dags completed", True)
        check("All 5 DAGs registered", len(dag_ids) == 5,
              f"got {len(dag_ids)}: {dag_ids}")
        for did in dag_ids:
            check(f"DAG '{did}' is Airflow DAG object",
                  hasattr(g[did], 'tasks'), f"type: {type(g[did])}")
        print(f"  Registered DAGs: {dag_ids}")
    except Exception as e:
        check("load_yaml_dags completed", False, f"Error: {e}")
        traceback.print_exc()


def test_task_operator_classes():
    print("\n" + "=" * 60)
    print("TEST 3: Task operator class resolution")
    print("=" * 60)

    for fname in YAML_FILES:
        fpath = os.path.join(TESTS_DIR, fname)
        with open(fpath) as f:
            raw = yaml.safe_load(f)

        try:
            factory = _DagFactory(config_filepath=fpath)
            dags = factory.build_dags()

            for dag_id, dag in dags.items():
                dag_config = raw[dag_id]
                for task_name, task_config in dag_config.get("tasks", {}).items():
                    expected_op = task_config.get("operator", "")
                    task = dag.get_task(task_name)
                    actual_class = f"{task.__class__.__module__}.{task.__class__.__name__}"
                    check(f"[{fname}] task '{task_name}' operator class",
                          actual_class == expected_op,
                          f"expected '{expected_op}', got '{actual_class}'")
        except Exception as e:
            check(f"[{fname}] operator class check", False, f"Error: {e}")
            traceback.print_exc()


def test_dag_properties():
    print("\n" + "=" * 60)
    print("TEST 4: DAG-level property validation")
    print("=" * 60)

    for fname in YAML_FILES:
        fpath = os.path.join(TESTS_DIR, fname)
        with open(fpath) as f:
            raw = yaml.safe_load(f)

        try:
            factory = _DagFactory(config_filepath=fpath)
            dags = factory.build_dags()

            for dag_id, dag in dags.items():
                dag_config = raw[dag_id]

                check(f"[{fname}] catchup = {dag_config.get('catchup', False)}",
                      dag.catchup == dag_config.get("catchup", False))

                expected_desc = dag_config.get("description", "")
                check(f"[{fname}] description set",
                      dag.description == expected_desc,
                      f"expected '{expected_desc}', got '{dag.description}'")

                expected_tags = set(dag_config.get("tags", []))
                actual_tags = set(dag.tags) if dag.tags else set()
                check(f"[{fname}] tags match (superset OK for dagfactory tag)",
                      expected_tags.issubset(actual_tags),
                      f"expected {expected_tags} ⊆ {actual_tags}")

        except Exception as e:
            check(f"[{fname}] DAG properties check", False, f"Error: {e}")
            traceback.print_exc()


def test_retry_config():
    print("\n" + "=" * 60)
    print("TEST 5: Retry configuration propagation")
    print("=" * 60)

    for fname in YAML_FILES:
        fpath = os.path.join(TESTS_DIR, fname)
        with open(fpath) as f:
            raw = yaml.safe_load(f)

        try:
            factory = _DagFactory(config_filepath=fpath)
            dags = factory.build_dags()

            for dag_id, dag in dags.items():
                dag_config = raw[dag_id]
                expected_retries = dag_config.get("default_args", {}).get("retries", 0)

                for task in dag.tasks:
                    check(f"[{fname}] task '{task.task_id}' retries = {expected_retries}",
                          task.retries == expected_retries,
                          f"got: {task.retries}")
                    break

        except Exception as e:
            check(f"[{fname}] retry config check", False, f"Error: {e}")
            traceback.print_exc()


def test_bootstrap_generate_dags():
    print("\n" + "=" * 60)
    print("TEST 6: Bootstrap generate_dags.py loading all YAMLs")
    print("=" * 60)

    bootstrap_dir = tempfile.mkdtemp()
    dataflow_subdir = os.path.join(bootstrap_dir, "dataflow")
    os.makedirs(dataflow_subdir, exist_ok=True)

    try:
        for fname in YAML_FILES:
            src = os.path.join(TESTS_DIR, fname)
            dst = os.path.join(dataflow_subdir, fname)
            shutil.copy2(src, dst)

        bootstrap_src = os.path.join(STUBS_DIR, "generate_dags.py")
        bootstrap_dst = os.path.join(bootstrap_dir, "generate_dags.py")
        shutil.copy2(bootstrap_src, bootstrap_dst)

        check("Bootstrap file exists", os.path.isfile(bootstrap_dst))
        check("YAML subdir populated",
              len(os.listdir(dataflow_subdir)) == len(YAML_FILES),
              f"got {len(os.listdir(dataflow_subdir))}")

        spec = importlib.util.spec_from_file_location("generate_dags", bootstrap_dst)
        mod = importlib.util.module_from_spec(spec)

        try:
            spec.loader.exec_module(mod)
            check("Bootstrap module loaded without error", True)
        except Exception as e:
            check("Bootstrap module loaded without error", False, f"Error: {e}")
            traceback.print_exc()

        dag_keys = [k for k in dir(mod) if k.startswith("dataflow__")]
        check("Bootstrap registered DAGs in globals",
              len(dag_keys) >= len(YAML_FILES),
              f"expected >= {len(YAML_FILES)}, got {len(dag_keys)}: {dag_keys}")

        for dk in dag_keys:
            obj = getattr(mod, dk)
            check(f"Bootstrap DAG '{dk}' is valid DAG object",
                  hasattr(obj, 'tasks'), f"type: {type(obj)}")

        print(f"  Bootstrap-registered DAGs: {dag_keys}")

    finally:
        shutil.rmtree(bootstrap_dir, ignore_errors=True)


def test_advanced_features_yaml():
    print("\n" + "=" * 60)
    print("TEST 7: Advanced features YAML with mapping_file references")
    print("=" * 60)

    fpath = os.path.join(TESTS_DIR, "advanced_features.yaml")
    with open(fpath) as f:
        raw = yaml.safe_load(f)

    dag_id = "dataflow__advanced_pipeline"
    check("Advanced YAML has expected DAG ID", dag_id in raw, f"keys: {list(raw.keys())}")

    dag_config = raw[dag_id]
    tasks = dag_config.get("tasks", {})

    check("Advanced DAG has sensor task", "wait_for_source_file" in tasks)
    check("Advanced DAG has spark extract task", "extract_hr__employees" in tasks)
    check("Advanced DAG has ingest task", "ingest_landing__raw_feed" in tasks)

    spark_task = tasks.get("extract_hr__employees", {})
    app_args = spark_task.get("application_args", [])
    check("Spark task has --mapping_file arg", "--mapping_file" in app_args,
          f"args: {app_args}")

    mapping_file_idx = app_args.index("--mapping_file") if "--mapping_file" in app_args else -1
    if mapping_file_idx >= 0 and mapping_file_idx + 1 < len(app_args):
        mapping_path = app_args[mapping_file_idx + 1]
        check("Mapping file path references mappings dir",
              "mappings/" in mapping_path, f"path: {mapping_path}")
        check("Mapping file exists on disk",
              os.path.isfile(mapping_path), f"path: {mapping_path}")

        with open(mapping_path) as f:
            mapping_data = json.load(f)
        check("Mapping JSON has pipeline field",
              "pipeline" in mapping_data, f"keys: {list(mapping_data.keys())}")
        check("Mapping JSON has columns field",
              "columns" in mapping_data and len(mapping_data["columns"]) > 0)
        check("Mapping JSON has cleansing rules",
              "cleansing" in mapping_data and len(mapping_data["cleansing"].get("rules", [])) > 0)
        check("Mapping JSON has data_quality rules",
              "data_quality" in mapping_data and len(mapping_data["data_quality"].get("rules", [])) > 0)
        check("Mapping JSON has masking rules",
              "masking" in mapping_data and len(mapping_data["masking"].get("rules", [])) > 0)

    spark_app = spark_task.get("application", "")
    check("Spark task application points to spark stub",
          "pipeline_spark.py" in spark_app, f"application: {spark_app}")

    check("Spark extract depends on sensor",
          "wait_for_source_file" in spark_task.get("dependencies", []))
    check("Ingest depends on sensor",
          "wait_for_source_file" in tasks.get("ingest_landing__raw_feed", {}).get("dependencies", []))

    try:
        factory = _DagFactory(config_filepath=fpath)
        dags = factory.build_dags()
        check("Advanced features DAG builds successfully", dag_id in dags)

        dag = dags[dag_id]
        check("Advanced DAG has 3 tasks", len(dag.tasks) == 3,
              f"got {len(dag.tasks)}")

        task_ids = sorted([t.task_id for t in dag.tasks])
        print(f"    Advanced DAG tasks: {task_ids}")
    except Exception as e:
        check("Advanced features DAG builds successfully", False, f"Error: {e}")
        traceback.print_exc()


def test_realistic_pipeline_tasks_callables():
    print("\n" + "=" * 60)
    print("TEST 8: Realistic pipeline_tasks.py has all expected callables")
    print("=" * 60)

    tasks_path = os.path.join(STUBS_DIR, "pipeline_tasks.py")
    check("pipeline_tasks.py exists", os.path.isfile(tasks_path))

    spec = importlib.util.spec_from_file_location("pipeline_tasks", tasks_path)
    mod = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
        check("pipeline_tasks.py imports without error", True)
    except Exception as e:
        check("pipeline_tasks.py imports without error", False, f"Error: {e}")
        traceback.print_exc()
        return

    expected_callables = [
        "adls_file_exists",
        "s3_file_exists",
        "sftp_file_exists",
        "local_file_exists",
        "nas_file_exists",
        "ingest_function",
    ]

    for fn_name in expected_callables:
        check(f"pipeline_tasks has callable '{fn_name}'",
              hasattr(mod, fn_name) and callable(getattr(mod, fn_name)),
              f"missing or not callable")

    check("local_file_exists accepts **kwargs",
          callable(getattr(mod, "local_file_exists", None)))
    check("ingest_function accepts positional + keyword args",
          callable(getattr(mod, "ingest_function", None)))


def test_pyspark_script_stub():
    print("\n" + "=" * 60)
    print("TEST 9: PySpark script stub has all expected functions")
    print("=" * 60)

    spark_path = os.path.join(STUBS_DIR, "pipeline_spark.py")
    check("pipeline_spark.py exists", os.path.isfile(spark_path))

    with open(spark_path) as f:
        content = f.read()

    expected_functions = [
        "def build_jdbc_url(",
        "def get_jdbc_driver(",
        "def get_connection_config(",
        "def extract_from_source(",
        "def write_to_target(",
        "def resolve_target_path(",
        "def apply_column_mapping(",
        "def apply_data_cleansing(",
        "def apply_data_quality_checks(",
        "def apply_masking(",
        "def main():",
    ]

    for fn_sig in expected_functions:
        check(f"pipeline_spark.py has '{fn_sig.strip()}'",
              fn_sig in content, "not found in file")

    check("pipeline_spark.py has argparse usage",
          "argparse.ArgumentParser" in content)
    check("pipeline_spark.py has --mapping_file argument",
          "--mapping_file" in content)
    check("pipeline_spark.py has JDBC URL building",
          "jdbc:oracle:thin" in content)
    check("pipeline_spark.py has __main__ guard",
          'if __name__ == "__main__":' in content)


def test_mapping_json_files():
    print("\n" + "=" * 60)
    print("TEST 10: Mapping JSON files are valid")
    print("=" * 60)

    mapping_files = [f for f in os.listdir(MAPPINGS_DIR) if f.endswith(".json")]
    check("Mapping directory has JSON files", len(mapping_files) >= 2,
          f"got {len(mapping_files)}: {mapping_files}")

    for mf in mapping_files:
        mpath = os.path.join(MAPPINGS_DIR, mf)
        try:
            with open(mpath) as f:
                data = json.load(f)
            check(f"[{mf}] valid JSON", True)
            check(f"[{mf}] has pipeline field", "pipeline" in data)
            check(f"[{mf}] has dataset field", "dataset" in data)
            check(f"[{mf}] has columns array", isinstance(data.get("columns"), list) and len(data["columns"]) > 0)

            for col in data["columns"]:
                check(f"[{mf}] column has source_column",
                      "source_column" in col, f"keys: {list(col.keys())}")
                check(f"[{mf}] column has target_column",
                      "target_column" in col, f"keys: {list(col.keys())}")
                break

        except json.JSONDecodeError as e:
            check(f"[{mf}] valid JSON", False, f"Error: {e}")
        except Exception as e:
            check(f"[{mf}] mapping file check", False, f"Error: {e}")


if __name__ == "__main__":
    print(f"Airflow version: {airflow.__version__}")
    print(f"Test YAML directory: {TESTS_DIR}")
    print(f"YAML files: {YAML_FILES}")

    test_individual_yaml_files()
    test_load_yaml_dags_bulk()
    test_task_operator_classes()
    test_dag_properties()
    test_retry_config()
    test_bootstrap_generate_dags()
    test_advanced_features_yaml()
    test_realistic_pipeline_tasks_callables()
    test_pyspark_script_stub()
    test_mapping_json_files()

    print("\n" + "=" * 60)
    print(f"RESULTS: {PASS} passed, {FAIL} failed")
    print("=" * 60)

    if ERRORS:
        print("\nFailed checks:")
        for e in ERRORS:
            print(e)
        sys.exit(1)
    else:
        print("\nAll checks passed!")
        sys.exit(0)
