#!/usr/bin/env python3
"""PySpark extraction and transformation script for pipeline: test_pipeline

Auto-generated by DataFlow. Handles:
  - RDBMS extraction via JDBC (Oracle, SQL Server, PostgreSQL, MySQL, MongoDB)
  - Target writes (local parquet, ADLS2 abfss://, S3 s3a://)
  - Column mapping/renaming via mapping JSON
  - Data cleansing transforms
  - Data quality validation
  - Security/masking transforms
"""

import argparse
import json
import logging
import os
import sys
import hashlib
from datetime import datetime

try:
    from pyspark.sql import SparkSession
    from pyspark.sql import functions as F
    from pyspark.sql.types import StringType
except ImportError:
    pass

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
)
logger = logging.getLogger("dataflow.spark.test_pipeline")


def build_jdbc_url(platform, host, port, database, extra_params=None):
    """Build JDBC connection URL based on source platform."""
    urls = {
        "oracle": f"jdbc:oracle:thin:@{host}:{port or 1521}:{database}",
        "sql_server": f"jdbc:sqlserver://{host}:{port or 1433};databaseName={database}",
        "postgresql": f"jdbc:postgresql://{host}:{port or 5432}/{database}",
        "mysql": f"jdbc:mysql://{host}:{port or 3306}/{database}",
    }
    url = urls.get(platform)
    if url is None:
        raise ValueError(f"Unsupported JDBC platform: {platform}")
    if extra_params:
        separator = "&" if "?" in url else (";" if platform == "sql_server" else "?")
        url += separator + extra_params
    return url


def get_jdbc_driver(platform):
    """Return the JDBC driver class for a given platform."""
    drivers = {
        "oracle": "oracle.jdbc.OracleDriver",
        "sql_server": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
        "postgresql": "org.postgresql.Driver",
        "mysql": "com.mysql.cj.jdbc.Driver",
    }
    driver = drivers.get(platform)
    if driver is None:
        raise ValueError(f"No JDBC driver configured for platform: {platform}")
    return driver


def get_connection_config(prefix):
    """Retrieve connection configuration from environment variables or Airflow Variables."""
    config = {}
    keys = ["HOST", "PORT", "DATABASE", "USERNAME", "PASSWORD", "EXTRA_PARAMS",
            "CONTAINER", "ACCOUNT_NAME", "ACCOUNT_KEY", "BUCKET", "REGION",
            "ACCESS_KEY", "SECRET_KEY", "CONNECTION_STRING"]
    for key in keys:
        env_key = f"DATAFLOW_{prefix}_{key}"
        val = os.environ.get(env_key)
        if val is None:
            try:
                from airflow.models import Variable
                val = Variable.get(env_key, default_var=None)
            except (ImportError, Exception):
                pass
        if val is not None:
            config[key.lower()] = val
    return config


def extract_from_source(spark, platform, schema, table, filter_query=None,
                        incremental_column=None, conn_config=None):
    """Extract data from an RDBMS source via JDBC or from MongoDB."""
    conn_config = conn_config or {}
    logger.info(f"Extracting {schema}.{table} from {platform}")

    if platform == "mongodb":
        mongo_uri = conn_config.get("connection_string") or (
            f"mongodb://{conn_config.get('username', 'root')}:{conn_config.get('password', '')}@"
            f"{conn_config.get('host', 'localhost')}:{conn_config.get('port', '27017')}/{conn_config.get('database', schema)}"
        )
        df = (spark.read
              .format("mongodb")
              .option("uri", mongo_uri)
              .option("database", schema)
              .option("collection", table)
              .load())
        if filter_query:
            df = df.filter(filter_query)
        logger.info(f"Extracted {df.count()} records from MongoDB {schema}.{table}")
        return df

    jdbc_url = build_jdbc_url(
        platform,
        conn_config.get("host", "localhost"),
        conn_config.get("port"),
        conn_config.get("database", schema),
        conn_config.get("extra_params"),
    )
    driver = get_jdbc_driver(platform)

    full_table = f"{schema}.{table}"
    if filter_query:
        dbtable = f"(SELECT * FROM {full_table} WHERE {filter_query}) sub"
    else:
        dbtable = full_table

    reader = (spark.read
              .format("jdbc")
              .option("url", jdbc_url)
              .option("dbtable", dbtable)
              .option("driver", driver)
              .option("user", conn_config.get("username", ""))
              .option("password", conn_config.get("password", "")))

    if incremental_column:
        reader = (reader
                  .option("partitionColumn", incremental_column)
                  .option("numPartitions", "10")
                  .option("lowerBound", "0")
                  .option("upperBound", "1000000"))

    df = reader.load()
    logger.info(f"Extracted {df.count()} records from {platform} {full_table}")
    return df


def write_to_target(df, target_platform, target_path, load_method, schema, table,
                    conn_config=None):
    """Write DataFrame to the target platform."""
    conn_config = conn_config or {}
    logger.info(f"Writing {schema}.{table} to {target_platform} at {target_path} ({load_method})")

    output_path = resolve_target_path(target_platform, target_path, schema, table, conn_config)
    write_mode = "overwrite" if load_method in ("overwrite", "full_refresh") else "append"

    if load_method == "upsert":
        logger.warning("Upsert mode: performing overwrite (full replace). "
                       "For true merge, use Delta Lake or database-native upsert.")
        write_mode = "overwrite"

    writer = df.write.mode(write_mode)

    if target_platform in ("adls2", "s3", "local_fs", "nas"):
        writer.option("header", "true").parquet(output_path)
        logger.info(f"Written parquet to {output_path}")
    else:
        writer.parquet(output_path)
        logger.info(f"Written parquet to {output_path}")


def resolve_target_path(target_platform, target_path, schema, table, conn_config):
    """Build the full output path based on target platform."""
    if target_path:
        base = target_path.rstrip("/")
    else:
        base = f"/data/output/{schema}/{table}"

    if target_platform == "adls2":
        account = conn_config.get("account_name", "storageaccount")
        container = conn_config.get("container", "datalake")
        if base.startswith("abfss://"):
            return base
        return f"abfss://{container}@{account}.dfs.core.windows.net/{base.lstrip('/')}"

    if target_platform == "s3":
        bucket = conn_config.get("bucket", "data-bucket")
        if base.startswith("s3a://") or base.startswith("s3://"):
            return base.replace("s3://", "s3a://")
        return f"s3a://{bucket}/{base.lstrip('/')}"

    if target_platform in ("local_fs", "nas"):
        return base

    return base


def apply_column_mapping(df, mapping_config):
    """Apply column mapping/renaming from mapping configuration."""
    if not mapping_config:
        return df
    mappings = mapping_config if isinstance(mapping_config, list) else mapping_config.get("mappings", [])
    for m in mappings:
        src_col = m.get("source_column") or m.get("source")
        tgt_col = m.get("target_column") or m.get("target")
        if src_col and tgt_col and src_col in df.columns:
            df = df.withColumnRenamed(src_col, tgt_col)
            logger.info(f"Renamed column: {src_col} -> {tgt_col}")
    return df


def apply_data_cleansing(df, cleansing_rules):
    """Apply data cleansing transforms to DataFrame columns."""
    if not cleansing_rules:
        return df
    rules = cleansing_rules if isinstance(cleansing_rules, list) else cleansing_rules.get("rules", [])
    for rule in rules:
        col_name = rule.get("column")
        transform = rule.get("transform") or rule.get("type")
        if not col_name or col_name not in df.columns:
            continue
        if transform == "trim":
            df = df.withColumn(col_name, F.trim(F.col(col_name)))
        elif transform == "lowercase":
            df = df.withColumn(col_name, F.lower(F.col(col_name)))
        elif transform == "uppercase":
            df = df.withColumn(col_name, F.upper(F.col(col_name)))
    return df


def apply_data_quality_checks(df, dq_rules, quarantine_path=None):
    """Run data quality checks and optionally quarantine failed rows."""
    if not dq_rules:
        return df, []
    rules = dq_rules if isinstance(dq_rules, list) else dq_rules.get("rules", [])
    violations = []
    for rule in rules:
        col_name = rule.get("column")
        check_type = rule.get("check") or rule.get("type")
        if not col_name or col_name not in df.columns:
            continue
        if check_type == "not_null":
            failed_df = df.filter(F.col(col_name).isNull())
            violation_count = failed_df.count()
            if violation_count > 0:
                violations.append({"column": col_name, "check": "not_null", "failures": violation_count})
                df = df.filter(F.col(col_name).isNotNull())
    return df, violations


def apply_masking(df, masking_rules):
    """Apply security/masking transforms to DataFrame columns."""
    if not masking_rules:
        return df
    rules = masking_rules if isinstance(masking_rules, list) else masking_rules.get("rules", [])
    for rule in rules:
        col_name = rule.get("column")
        mask_type = rule.get("type") or rule.get("mask_type")
        if not col_name or col_name not in df.columns:
            continue
        if mask_type == "redact":
            redact_val = rule.get("value", "***REDACTED***")
            df = df.withColumn(col_name, F.lit(redact_val))
    return df


def main():
    parser = argparse.ArgumentParser(description="DataFlow PySpark extraction and transformation")
    parser.add_argument("--source_platform", required=True,
                        choices=["oracle", "sql_server", "postgresql", "mysql", "mongodb"],
                        help="Source database platform")
    parser.add_argument("--target_platform", required=True,
                        choices=["local_fs", "adls2", "s3", "nas"],
                        help="Target storage platform")
    parser.add_argument("--schema", required=True, help="Source schema name")
    parser.add_argument("--table", required=True, help="Source table name")
    parser.add_argument("--load_method", default="append",
                        choices=["append", "overwrite", "full_refresh", "upsert"],
                        help="Load method for target write")
    parser.add_argument("--filter_query", default=None, help="SQL WHERE clause for filtering")
    parser.add_argument("--incremental_column", default=None,
                        help="Column for incremental/partition-based reads")
    parser.add_argument("--target_path", default=None, help="Target output path")
    parser.add_argument("--mapping_file", default=None,
                        help="Path to JSON mapping file for column mapping, cleansing, DQ, masking")
    args = parser.parse_args()

    logger.info(f"Starting extraction: {args.schema}.{args.table} from {args.source_platform} to {args.target_platform}")

    spark = (SparkSession.builder
             .appName(f"dataflow_{args.schema}_{args.table}")
             .getOrCreate())

    try:
        source_config = get_connection_config("SOURCE")
        target_config = get_connection_config("TARGET")

        df = extract_from_source(
            spark, args.source_platform, args.schema, args.table,
            filter_query=args.filter_query,
            incremental_column=args.incremental_column,
            conn_config=source_config,
        )

        mapping_config = None
        if args.mapping_file:
            logger.info(f"Loading mapping file: {args.mapping_file}")
            with open(args.mapping_file, "r") as f:
                mapping_config = json.load(f)

        if mapping_config and mapping_config.get("mappings"):
            df = apply_column_mapping(df, mapping_config)

        if mapping_config and mapping_config.get("cleansing"):
            df = apply_data_cleansing(df, mapping_config["cleansing"])

        if mapping_config and mapping_config.get("data_quality"):
            quarantine_path = mapping_config.get("quarantine_path")
            df, violations = apply_data_quality_checks(
                df, mapping_config["data_quality"], quarantine_path=quarantine_path
            )

        if mapping_config and mapping_config.get("masking"):
            df = apply_masking(df, mapping_config["masking"])

        target_path = args.target_path or f"/data/output/{args.schema}/{args.table}"
        write_to_target(
            df, args.target_platform, target_path, args.load_method,
            args.schema, args.table, conn_config=target_config,
        )

        logger.info(f"Pipeline complete: {args.schema}.{args.table}")
    except Exception as e:
        logger.error(f"Pipeline failed: {e}")
        raise
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
