"""
Pipeline tasks for: test_pipeline
Auto-generated by DataFlow

Source: local_fs_source (local_fs)
Target: local_fs_target (local_fs)

Required packages:
  - pandas
"""

import logging
from airflow.models import Variable

logger = logging.getLogger("airflow.task.test_pipeline")


# --- Sensor callable: local_file_exists ---

def local_file_exists(**kwargs):
    """Check if a file exists on the local filesystem."""
    import glob as glob_module
    import os

    watch_path = os.environ.get('SOURCE_WATCH_PATH', Variable.get('source_watch_path', default_var='/data/inbound/*'))

    try:
        if '*' in watch_path or '?' in watch_path:
            matches = glob_module.glob(watch_path)
            found = len(matches) > 0
        else:
            found = os.path.exists(watch_path)
        logger.info(f"Local filesystem sensor check: path={watch_path}, found={found}")
        return found
    except Exception as e:
        logger.error(f"Local filesystem sensor error: {e}")
        return False


# --- Sensor callable: adls_file_exists ---

def adls_file_exists(**kwargs):
    """Check if a file exists in Azure ADLS Gen2."""
    try:
        from azure.storage.filedatalake import DataLakeServiceClient
    except ImportError:
        logger.warning("azure-storage-file-datalake not installed, returning True for test")
        return True
    import os

    account_name = os.environ.get('ADLS_ACCOUNT_NAME', Variable.get('adls_account_name', default_var=''))
    account_key = os.environ.get('ADLS_ACCOUNT_KEY', Variable.get('adls_account_key', default_var=''))
    container = os.environ.get('ADLS_CONTAINER', Variable.get('adls_container', default_var='landing'))
    watch_path = os.environ.get('SOURCE_WATCH_PATH', Variable.get('source_watch_path', default_var='/inbound/'))

    if not account_name or not account_key:
        logger.warning("ADLS credentials not configured, skipping sensor check")
        return False

    try:
        service_client = DataLakeServiceClient(
            account_url=f"https://{account_name}.dfs.core.windows.net",
            credential=account_key
        )
        fs_client = service_client.get_file_system_client(container)
        paths = list(fs_client.get_paths(path=watch_path, recursive=False))
        found = len(paths) > 0
        logger.info(f"ADLS sensor check: container={container}, path={watch_path}, found={found}")
        return found
    except Exception as e:
        logger.error(f"ADLS sensor error: {e}")
        return False


# --- Sensor callable: s3_file_exists ---

def s3_file_exists(**kwargs):
    """Check if a file exists in AWS S3."""
    try:
        import boto3
    except ImportError:
        logger.warning("boto3 not installed, returning True for test")
        return True
    import os

    bucket = os.environ.get('S3_BUCKET', Variable.get('s3_bucket', default_var=''))
    prefix = os.environ.get('S3_PREFIX', Variable.get('s3_prefix', default_var='inbound/'))
    region = os.environ.get('AWS_REGION', Variable.get('aws_region', default_var='us-east-1'))

    if not bucket:
        logger.warning("S3 bucket not configured, skipping sensor check")
        return False

    try:
        s3 = boto3.client('s3', region_name=region)
        response = s3.list_objects_v2(Bucket=bucket, Prefix=prefix, MaxKeys=1)
        found = response.get('KeyCount', 0) > 0
        logger.info(f"S3 sensor check: bucket={bucket}, prefix={prefix}, found={found}")
        return found
    except Exception as e:
        logger.error(f"S3 sensor error: {e}")
        return False


# --- Sensor callable: sftp_file_exists ---

def sftp_file_exists(**kwargs):
    """Check if a file exists on an SFTP server."""
    try:
        import paramiko
    except ImportError:
        logger.warning("paramiko not installed, returning True for test")
        return True
    import os

    host = os.environ.get('SFTP_HOST', Variable.get('sftp_host', default_var=''))
    port = int(os.environ.get('SFTP_PORT', Variable.get('sftp_port', default_var='22')))
    username = os.environ.get('SFTP_USERNAME', Variable.get('sftp_username', default_var=''))
    password = os.environ.get('SFTP_PASSWORD', Variable.get('sftp_password', default_var=''))
    key_path = os.environ.get('SFTP_KEY_PATH', Variable.get('sftp_key_path', default_var=''))
    watch_path = os.environ.get('SOURCE_WATCH_PATH', Variable.get('source_watch_path', default_var='/inbound/'))

    if not host or not username:
        logger.warning("SFTP credentials not configured, skipping sensor check")
        return False

    try:
        transport = paramiko.Transport((host, port))
        if key_path:
            pkey = paramiko.RSAKey.from_private_key_file(key_path)
            transport.connect(username=username, pkey=pkey)
        else:
            transport.connect(username=username, password=password)

        sftp = paramiko.SFTPClient.from_transport(transport)
        try:
            entries = sftp.listdir(watch_path)
            found = len(entries) > 0
            logger.info(f"SFTP sensor check: host={host}, path={watch_path}, found={found}")
            return found
        finally:
            sftp.close()
            transport.close()
    except Exception as e:
        logger.error(f"SFTP sensor error: {e}")
        return False


# --- Sensor callable: nas_file_exists ---

def nas_file_exists(**kwargs):
    """Check if a file exists on a NAS / network share."""
    import glob as glob_module
    import os

    watch_path = os.environ.get('SOURCE_WATCH_PATH', Variable.get('source_watch_path', default_var='/mnt/nas/inbound/*'))

    try:
        if '*' in watch_path or '?' in watch_path:
            matches = glob_module.glob(watch_path)
            found = len(matches) > 0
        else:
            found = os.path.exists(watch_path)
        logger.info(f"NAS sensor check: path={watch_path}, found={found}")
        return found
    except Exception as e:
        logger.error(f"NAS sensor error: {e}")
        return False


# --- Ingest function ---

def ingest_function(source_path, dataset_key, load_method="append", target_path="", **kwargs):
    """
    Ingest flat files from source to target.

    Args:
        source_path: Path or pattern for source file(s)
        dataset_key: Unique dataset identifier
        load_method: One of 'append', 'overwrite', 'upsert'
        target_path: Target location override
    """
    import os

    logger.info(f"Starting ingestion: dataset={dataset_key}, source={source_path}, method={load_method}")

    import pandas as pd

    file_path = source_path
    delimiter = os.environ.get('FILE_DELIMITER', Variable.get('file_delimiter', default_var=','))
    encoding = os.environ.get('FILE_ENCODING', Variable.get('file_encoding', default_var='utf-8'))

    if '*' in file_path or '?' in file_path:
        import glob as glob_module
        files = sorted(glob_module.glob(file_path))
        if not files:
            raise FileNotFoundError(f"No files matched pattern: {file_path}")
        file_path = files[0]
        logger.info(f"Matched {len(files)} file(s), processing first: {file_path}")

    logger.info(f"Reading CSV file: {file_path}")
    df = pd.read_csv(file_path, delimiter=delimiter, encoding=encoding)
    logger.info(f"Read {len(df)} records from: {file_path}")

    import shutil
    from pathlib import Path

    dest_dir = target_path if target_path else f"/data/output/{dataset_key}"
    Path(dest_dir).mkdir(parents=True, exist_ok=True)

    if load_method == 'overwrite':
        output_file = os.path.join(dest_dir, f"{dataset_key}.parquet")
    else:
        from datetime import datetime as dt
        ts = dt.now().strftime('%Y%m%d_%H%M%S')
        output_file = os.path.join(dest_dir, f"{dataset_key}_{ts}.parquet")

    df.to_parquet(output_file, index=False)
    logger.info(f"Written to local: {output_file}")

    logger.info(f"Ingestion complete: dataset={dataset_key}, records={len(df)}, method={load_method}")
    return {"dataset": dataset_key, "records": len(df), "load_method": load_method}
